### ISSUE TITLE
建立工程失败

### ISSUE THREAD

**Issue by lmule** [DamianSheldon/Xcode-6-Project-Templates#1]
hi，您好，我刚试了下您的工程模板，在xcode7下面貌似失败了，Controllers、General应该是文件夹吧，但我建立之后貌似是文件呢？hi，您好，我刚试了下您的工程模板，在xcode7下面貌似失败了，Controllers、General应该是文件夹吧，但我建立之后貌似是文件呢？

**Comment by DamianSheldon** [comment]
哦，之前是为 Xcode 6创建的，没在 Xcode 7 上测试过，有空我更新下，你可以先试下 [liftoff](https://github.com/thoughtbot/liftoff)。

**Comment by lmule** [comment]
get了
谢谢哈
